# Remove this line:
# version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/userdb
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=8080
    networks:
      - backend-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  backend-network:
    driver: bridge